### ISSUE TITLE
Doesn't compile with OTP28.0

### ISSUE THREAD

**Issue by tanguilp** [jonasschmidt/ex_json_schema#95]
Due to [changes in OTP28](https://www.erlang.org/blog/highlights-otp-28/#notable-changes) Regex library `re`, this library no longer compiles:

```
$ mix deps.compile ex_json_schema
==> ex_json_schema
Compiling 39 files (.ex)

== Compilation error in file lib/ex_json_schema/validator/format.ex ==
** (ArgumentError) cannot inject attribute @formats into function/macro because ~r/^[\w!#$%&'*+\/=?`{|}~^-]+(?:\.[\w!#$%&'*+\/=?`{|}~^-]+)*@(?:[A-Z0-9-]+\.)+[a-z]{2,}$/i contains a reference (#Reference<0.3544389747.2255880199.256432>) and therefore it cannot be escaped (it must be defined within a function instead). The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
    (elixir 1.19.0-rc.0) lib/kernel.ex:3872: Kernel.do_at_escape/2
    (elixir 1.19.0-rc.0) expanding macro: Kernel.@/1
    lib/ex_json_schema/validator/format.ex:86: ExJsonSchema.Validator.Format.do_validate/3
could not compile dependency :ex_json_schema, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_json_schema --force", update it with "mix deps.update ex_json_schema" or clean it with "mix deps.clean ex_json_schema"
```

In a nutshell: it is no longer possible to declare regexes as module attributes.

**Comment by tanguilp** [comment]
Apologies for making you lose some time. You're right, it compiles properly now that I've forced the version.

**Comment by jonasschmidt** [comment]
No worries, I'm glad we figured this out 👍
